### ISSUE TITLE
Disable sign up page

### ISSUE THREAD

**Issue by godfreym** [Furaha/3sixd#17]
### Note:
The admin would prefer to be given the user name +  password for login credentials to the app and then given a link where he can change the password when he needs to do so

### Tasks Involved:
- [x] Disable the sign up page
- [x] Add default user-name and password for an admin
- [x] Add a link for the admin to change his password
- [x] Make sure the default company when accessing the app is 3sixD

**Comment by godfreym** [comment]
@arafatm Done and demoed
